repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-docstring-first
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        args:
          - '--config=.flake8'
        additional_dependencies: [ flake8-docstrings, flake8-quotes, flake8-print, pep8-naming,
                                   flake8-absolute-import, flake8-comprehensions, flake8-commas,
                                   flake8-multiline-containers, flake8-functions, flake8-variables-names,
                                    flake8-expression-complexity, flake8-cognitive-complexity]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        entry: mypy .
        pass_filenames: false
#        verbose: true
#        entry: bash -c 'mypy "$@" || true' --
#  - repo: https://github.com/asottile/pyupgrade
#    rev: v2.32.0
#    hooks:
#      - id: pyupgrade
  - repo: https://github.com/DanyloSolohub/prehooks
    rev: 1.0.1
    hooks:
      - id: task_id-in-branch-name
      - id: add-msg-issue-prefix
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
