repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-docstring-first
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.226'
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        args:
          - '--config=.flake8'
        additional_dependencies: [ flake8-absolute-import, flake8-multiline-containers,
                                   flake8-functions, flake8-variables-names,
                                   flake8-expression-complexity, flake8-cognitive-complexity ]
  - repo: https://github.com/DanyloSolohub/prehooks
    rev: 1.0.1
    hooks:
      - id: task_id-in-branch-name
      - id: add-msg-issue-prefix
