repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-docstring-first
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.216
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: [ "--force-exclude" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        args: [ --ignore-missing-imports ]
#        verbose: true
#        entry: bash -c 'mypy "$@" || true' --
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/DanyloSolohub/prehooks
    rev: 1.0.1
    hooks:
      - id: task_id-in-branch-name
      - id: add-msg-issue-prefix
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ '--settings-file', '.isort.cfg' ]
        name: isort (python)
