[tool.black]
line-length = 120
target-version = ['py38']
skip-string-normalization = true
skip-magic-trailing-comma = true

[tool.isort]
line_length = 120
multi_line_output = 5
include_trailing_comma = true
force_grid_wrap = 0
ensure_newline_before_comments = true
use_parentheses = true
add_imports = ['from __future__ import annotations']
skip_gitignore = true

[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
allow_redefinition = true
warn_no_return = false
check_untyped_defs = true
disallow_untyped_defs = true
warn_unused_ignores = true
exclude = ['venv/']
